[package]
name = "swarp"
version = "0.2.0"
authors = ["Eduardo Tongson <propolice@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1.0", features = ["fs", "sync", "time"] }
warp = "0.3.1"

[profile.release]
codegen-units = 1
lto = true
debug = false
