[package]
name = "swarp"
version = "0.1.0"
authors = ["Eduardo Tongson <propolice@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["full"] }
warp = "0.2.5"

[profile.release]
codegen-units = 1
lto = true
debug = false
