[package]
name = "warp-cwd"
version = "0.1.0"
authors = ["Eduardo Tongson <propolice@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["full"] }
warp = "0.2.5"
log = "0.4"
pretty_env_logger = "0.3"
